### ISSUE TITLE
STEP entity support

### ISSUE THREAD

**Issue by andybak** [FKI-HTW/UnitySTEPImporter#1]
I just had a brief look at the STEP spec and it's a monster. Are there any details about what parts of it is supported/unsupported by UnitySTEPImporter?

**Comment by jKnepel** [comment]
This package is currently made up of leftovers of an older project, which were extracted into a separate package. There is currently a new version of the DLLs and Importer in the works. 
But because they are being created by an outside collaborator and the DLLs are closed-source, I can't give any detailed explanation on the supported specs. I have, however, messaged the authors about the specs and can hopefully give a better answer soon. The new version of the STEP Importer is expected to have its first version published early next year, and should come with a better documentation.
We are currently using this package to import STEP-Files, with the DLLs creating the meshes which adhere to the model's Assembly structure. The DLLs also support multiple automatically created LODs, retaining of colour and of the individual model names.

**Comment by andybak** [comment]
> But because they are being created by an outside collaborator and the DLLs are closed-source

Ah. I'm specifically looking for an open source implementation. Shame!

**Comment by utewagner** [comment]
There is a misunderstanding. Everything is open source. The dll we are developing for reading STEP files is based on OpenCASCADE.
